-- Create the leads table
create table public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  whatsapp text not null,
  nps integer,
  nps_reason text,
  role text,
  challenges text,
  question text,
  lgpd boolean default false
);

-- Set up Row Level Security (RLS)
alter table public.leads enable row level security;

-- Allow anonymous inserts (for the landing page)
create policy "Enable insert for anon users"
on public.leads
for insert
to anon
with check (true);

-- Allow read access only to authenticated users (optional, for your dashboard)
create policy "Enable read access for authenticated users"
on public.leads
for select
to authenticated
using (true);
